" DARREN TAN
" dyztan@gmail.com
" https://github.com/Tanbourine/dotfiles

if has("unix")
	source $HOME/.vim/vimrc/plugins.vim
	source $HOME/.vim/vimrc/plugin_configs.vim
	source $HOME/.vim/vimrc/settings.vim
elseif has ("win32")
	"user must change filename to _vimrc
	source $HOME/vimfiles/vimrc/plugins.vim
	source $HOME/vimfiles/vimrc/plugin_configs.vim
	source $HOME/vimfiles/vimrc/settings.vim
endif
